import Head from "next/head"
import Message from "../components/message"
import { useEffect, useState } from "react"
import { db, auth } from "../utils/firebase"
import { collection, onSnapshot, orderBy, query } from "firebase/firestore"
import Link from "next/link"
import { useAuthState } from "react-firebase-hooks/auth"
import { useRouter } from "next/router"

export default function Home() {
  const router = useRouter()

  // create a state with all the post
  const [allPosts, setAllPosts] = useState([])
  const [user, loading] = useAuthState(auth)

  // checks if user is logged in or not if not then it will send them to login page

  const ifUser = async () => {
    if (!user) router.push("/auth/login")
  }

  // get all the posts from the database from every user
  const getPosts = async () => {
    const collectionRef = collection(db, "posts")
    const q = query(collectionRef, orderBy("timestamp", "desc"))
    const unsubscribe = onSnapshot(q, (snapshot) => {
      setAllPosts(
        snapshot.docs.map((doc) => ({
          ...doc.data(),
          id: doc.id,
        }))
      )
    })
    return unsubscribe
  }

  useEffect(() => {
    if (user) {
      getPosts()
    } else {
      ifUser()
    }
  }, [user, loading])

  return (
    <div>
      <Head>
        <title>Quote Vault</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-12 text-lg font-medium">
        <h2 className="mb-5">See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post}>
            <Link href={{ pathname: `/${post.id}`, query: { ...post } }}>
              <button>
                {post.comments?.length > 0 ? post.comments.length : 0} comments
              </button>
            </Link>
          </Message>
        ))}
      </div>
    </div>
  )
}
